spring.application.name=Course-Work
spring.datasource.url=jdbc:h2:file:./data/trainsorty_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# 4. ??????? H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true
# ?????????? ??????? H2 (?????? ????? http://localhost:8080/h2-console)
